# Generated by Django 2.2.4 on 2019-12-27 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocktailName', models.CharField(max_length=50)),
                ('howToMake', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='liquor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquorName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='liquor_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseSpirit', models.CharField(max_length=50)),
                ('cocktailType', models.CharField(max_length=50)),
                ('served', models.CharField(max_length=50)),
                ('preparation', models.CharField(max_length=50)),
                ('stregth', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('cocktailName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bixbar.cocktail')),
            ],
        ),
        migrations.CreateModel(
            name='ingredient_liquor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquorml', models.IntegerField(default=0)),
                ('cocktailName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bixbar.cocktail')),
                ('liquorName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bixbar.liquor')),
            ],
        ),
        migrations.CreateModel(
            name='glass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glassName', models.CharField(max_length=20)),
                ('cocktailName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bixbar.cocktail')),
            ],
        ),
        migrations.CreateModel(
            name='garnish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garnishName', models.CharField(max_length=50)),
                ('cocktailName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bixbar.cocktail')),
            ],
        ),
    ]
