# Generated by Django 2.2.4 on 2019-12-28 08:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bixbar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glass',
            name='cocktailName',
        ),
        migrations.RemoveField(
            model_name='ingredient_liquor',
            name='cocktailName',
        ),
        migrations.RemoveField(
            model_name='ingredient_liquor',
            name='liquorName',
        ),
        migrations.RemoveField(
            model_name='liquor_profile',
            name='cocktailName',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='img',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='howToMake',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.DeleteModel(
            name='garnish',
        ),
        migrations.DeleteModel(
            name='glass',
        ),
        migrations.DeleteModel(
            name='ingredient_liquor',
        ),
        migrations.DeleteModel(
            name='liquor',
        ),
        migrations.DeleteModel(
            name='liquor_profile',
        ),
    ]
