# Generated by Django 2.2.4 on 2019-12-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bixbar', '0002_auto_20191228_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='howToMake',
            field=models.CharField(max_length=200),
        ),
    ]
