# Generated by Django 2.2.4 on 2019-12-29 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bixbar', '0003_auto_20191228_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktail',
            old_name='howToMake',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='cocktail',
            old_name='cocktailName',
            new_name='title',
        ),
    ]
