# Generated by Django 2.2.4 on 2019-12-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bixbar', '0004_auto_20191229_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='Glass',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
