# Generated by Django 2.2.4 on 2019-12-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bixbar', '0005_cocktail_glass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='Glass',
            field=models.TextField(null=True),
        ),
    ]
