# Generated by Django 2.2.4 on 2019-12-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bixbar', '0006_auto_20191229_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='Profile_value',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='recipe',
            field=models.TextField(),
        ),
    ]
