# Generated by Django 2.2.4 on 2019-12-29 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bixbar', '0007_auto_20191229_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktail',
            old_name='Profile_value',
            new_name='Profile',
        ),
    ]
