# Generated by Django 2.2.4 on 2019-12-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bixbar', '0011_auto_20191229_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='riquor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='riquorml',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
