# Generated by Django 2.2.4 on 2019-12-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bixbar', '0012_auto_20191229_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktail',
            old_name='profile',
            new_name='baseSpirit',
        ),
        migrations.RenameField(
            model_name='cocktail',
            old_name='Garnish',
            new_name='garnish',
        ),
        migrations.RenameField(
            model_name='cocktail',
            old_name='Glass',
            new_name='glass',
        ),
        migrations.RenameField(
            model_name='cocktail',
            old_name='riquor',
            new_name='liquor',
        ),
        migrations.RenameField(
            model_name='cocktail',
            old_name='riquorml',
            new_name='liquorml',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='brands',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='cocktailType',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='difficulty',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='flavor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='hours',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='preparation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='served',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='strength',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
