# Generated by Django 2.2.4 on 2019-12-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bixbar', '0020_auto_20191229_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='cocktail2',
            field=models.ManyToManyField(to='bixbar.Cocktail'),
        ),
    ]
