# Generated by Django 2.2.4 on 2019-12-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bixbar', '0023_auto_20191229_1656'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeModel',
        ),
    ]
