# Generated by Django 2.2.4 on 2019-12-29 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bixbar', '0024_delete_recipemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe2', models.TextField(null=True)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bixbar.Cocktail')),
            ],
        ),
    ]
