# Generated by Django 2.2.4 on 2019-12-29 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bixbar', '0027_auto_20191229_1727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeModel',
        ),
    ]
