# Generated by Django 2.2.4 on 2020-02-27 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bixbar', '0029_foods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='ingredientfoods',
            new_name='ingFoodsUnit',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='ingredientfoodsml',
            new_name='ingfoods',
        ),
    ]
