# Generated by Django 2.2.4 on 2020-03-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bixbar', '0031_auto_20200227_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='matchCocktails',
            field=models.CharField(max_length=50),
        ),
    ]
