# Generated by Django 2.2.4 on 2019-12-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bixbar', '0008_auto_20191229_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='Garnish',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='Glass',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
