# Generated by Django 2.2.4 on 2019-12-29 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bixbar', '0010_auto_20191229_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktail',
            old_name='Profile',
            new_name='profile',
        ),
    ]
