# Generated by Django 2.2.4 on 2019-12-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bixbar', '0013_auto_20191229_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe2', models.TextField()),
                ('cocktail', models.ManyToManyField(to='bixbar.Cocktail')),
            ],
        ),
    ]
