# Generated by Django 2.2.4 on 2019-12-29 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bixbar', '0026_auto_20191229_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='cocktail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bixbar.Cocktail'),
        ),
    ]
