# Generated by Django 2.2.4 on 2020-02-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bixbar', '0028_delete_recipemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodsTitle', models.CharField(max_length=50)),
                ('ingredientfoodsml', models.CharField(max_length=50, null=True)),
                ('ingredientfoods', models.CharField(max_length=50, null=True)),
                ('matchCocktails', models.CharField(max_length=50, null=True)),
                ('matchLiquor', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
