# Generated by Django 2.2.4 on 2020-02-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bixbar', '0030_auto_20200227_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='ingfoods',
            new_name='ingFoods',
        ),
    ]
