# Generated by Django 2.2.4 on 2020-03-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bixbar', '0032_auto_20200318_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchLiquor', models.CharField(max_length=50)),
                ('foodsTitle', models.CharField(max_length=50)),
                ('ingFoods', models.CharField(max_length=50, null=True)),
                ('ingFoodsUnit', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchCocktails', models.CharField(max_length=50)),
                ('foodsTitle', models.CharField(max_length=50)),
                ('ingFoods', models.CharField(max_length=50, null=True)),
                ('ingFoodsUnit', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Foods',
        ),
    ]
